### ISSUE TITLE
DIME RF Scores 

### ISSUE THREAD

**Issue by jkortner** [SinaMaria412/predictors_of_polling_errors#29]
Get random forest (RF) predictions from DIME database (Bonica, 2018) to measure ideology for Senate candidates (up to 2019, i.e. including election in 2018).

Reference: 
Bonica, A. (2018). Inferring Roll‐Call Scores from Campaign Contributions Using Supervised Machine Learning. American Journal of Political Science, 62(4), 830-848. https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12376

**Comment by SinaMaria412** [comment]
the code for mergibg rf predictions can be found in us_senate/code/covariates/merge_rf_scores.R

**Comment by SinaMaria412** [comment]
the code for merging rf predictions can be found in us_senate/code/covariates/merge_rf_scores.R
